// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraitBrowserWebApp.Data;

#nullable disable

namespace TraitBrowserWebApp.Migrations.LocBuff
{
    [DbContext(typeof(LocBuffContext))]
    partial class LocBuffContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("TraitBrowserWebApp.Models.LocBuff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("English")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SChinese")
                        .HasColumnType("TEXT");

                    b.Property<string>("TChinese")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocBuff");
                });
#pragma warning restore 612, 618
        }
    }
}
