// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraitBrowserWebApp.Data;

#nullable disable

namespace TraitBrowserWebApp.Migrations.TraitBrowser
{
    [DbContext(typeof(TraitBrowserContext))]
    [Migration("20250221024255_AddLocIdxToTrait")]
    partial class AddLocIdxToTrait
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("TraitBrowser.Models.Trait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TraitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("locInfo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trait");
                });
#pragma warning restore 612, 618
        }
    }
}
